"""
train_dir_gesture_svm.py — 方向手势 SVM 分类器训练 & C代码导出
==============================================================
用法：
  python train_dir_gesture_svm.py [--data dir_gesture_data.csv] [--out dir_gesture_model.h]

流程：
  1. 读取 collect_dir_gesture.py 采集的 CSV
  2. 特征标准化（StandardScaler）
  3. 训练 LinearSVC（线性 SVM）
  4. 5折交叉验证打印准确率
  5. 导出 dir_gesture_model.h（C语言数组，直接 #include 到 STM32）

这组工具与原有 gesture_model.h（握拳/张开等）完全独立。
"""

import argparse
import os
import sys
import numpy as np

# ---------------------------------------------------------------------------
DIR_NAMES  = {0: "up", 1: "down", 2: "left", 3: "right"}
N_FEATURES = 10   # [f0x,f0y,f1x,f1y,f2x,f2y,f3x,f3y,roll,pitch]（通道4已禁用）
N_CLASSES  = 4
# ---------------------------------------------------------------------------


def load_data(csv_path: str):
    """加载 CSV 并返回特征矩阵 X 和标签向量 y"""
    try:
        import pandas as pd
    except ImportError:
        print("[错误] 请安装 pandas：pip install pandas")
        sys.exit(1)

    if not os.path.exists(csv_path):
        print(f"[错误] 找不到数据文件：{csv_path}")
        sys.exit(1)

    # 自动检测有无表头
    df_peek = pd.read_csv(csv_path, nrows=1)
    try:
        float(df_peek.columns[0])
        has_header = False
    except ValueError:
        has_header = True

    if has_header:
        df = pd.read_csv(csv_path)
    else:
        print("[信息] 检测到无表头 CSV，自动分配列名")
        df = pd.read_csv(csv_path, header=None)
        if len(df.columns) != N_FEATURES + 1:
            print(f"[错误] 期望 {N_FEATURES+1} 列，实际 {len(df.columns)} 列")
            sys.exit(1)
        df.columns = ["f0x", "f0y", "f1x", "f1y", "f2x", "f2y",
                      "f3x", "f3y", "roll", "pitch", "label"]

    FEATURE_COLS = ["f0x", "f0y", "f1x", "f1y", "f2x", "f2y",
                    "f3x", "f3y", "roll", "pitch"]

    if "label" not in df.columns:
        print("[错误] CSV 缺少 label 列")
        sys.exit(1)

    # 丢弃 NaN 行
    before = len(df)
    df = df.dropna()
    dropped = before - len(df)
    if dropped > 0:
        print(f"[清理] 丢弃 {dropped} 行不完整数据（NaN）")

    X = df[FEATURE_COLS].values.astype(np.float32)
    y = df["label"].values.astype(int)

    print(f"[数据] {len(X)} 帧，{N_FEATURES} 维特征")
    print("各方向样本数：")
    for lbl, name in DIR_NAMES.items():
        cnt = np.sum(y == lbl)
        bar = "█" * min(cnt // 10, 20)
        tip = "✓" if cnt >= 200 else f"（建议 ≥ 200）"
        print(f"  [{lbl}] {name:6s}: {cnt:4d} 帧  {bar}  {tip}")

    # 检查是否有缺失标签
    for lbl in DIR_NAMES:
        if np.sum(y == lbl) == 0:
            print(f"\n[错误] 标签 {lbl}（{DIR_NAMES[lbl]}）没有数据，请先采集！")
            sys.exit(1)

    return X, y


def train_and_evaluate(X, y):
    try:
        from sklearn.svm import LinearSVC
        from sklearn.preprocessing import StandardScaler
        from sklearn.pipeline import Pipeline
        from sklearn.model_selection import cross_val_score, StratifiedKFold
    except ImportError:
        print("[错误] 请安装 scikit-learn：pip install scikit-learn")
        sys.exit(1)

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("svm",    LinearSVC(C=1.0, max_iter=5000, random_state=42)),
    ])

    cv     = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y, cv=cv, scoring="accuracy")

    print(f"\n[评估] 5折交叉验证准确率：")
    for i, s in enumerate(scores):
        print(f"  第{i+1}折: {s*100:.1f}%")
    print(f"  平均: {scores.mean()*100:.1f}%  ± {scores.std()*100:.1f}%")

    if scores.mean() < 0.85:
        print("\n[警告] 平均准确率 < 85%，建议：")
        print("  1. 增加每方向采集帧数（目标 ≥ 200 帧）")
        print("  2. 采集时保持手势绝对静止，不同次采集保持同一手形")
        print("  3. 确认4种手势彼此区分度足够大")

    pipeline.fit(X, y)
    scaler = pipeline.named_steps["scaler"]
    svm    = pipeline.named_steps["svm"]
    return scaler, svm, scores.mean()


def export_c_header(scaler, svm, output_path: str, accuracy: float):
    """
    导出 dir_gesture_model.h：
      - StandardScaler 均值/标准差（前缀 dg_）
      - LinearSVC 权重矩阵/偏置（前缀 dg_）
      - DirGesture_Classify() 内联推理函数
    前缀 dg_ 避免与 gesture_model.h（gm_）或 swipe_model.h（sm_）冲突。
    """
    mean_  = scaler.mean_.astype(np.float32)
    scale_ = scaler.scale_.astype(np.float32)
    W      = svm.coef_.astype(np.float32)         # (N_CLASSES, N_FEATURES)
    b      = svm.intercept_.astype(np.float32)    # (N_CLASSES,)

    def arr1d(arr, name):
        vals = ", ".join(f"{v:.6f}f" for v in arr.flatten())
        return f"static const float {name}[{len(arr)}] = {{{vals}}};"

    def arr2d(arr, name):
        rows, cols = arr.shape
        vals = ", ".join(f"{v:.6f}f" for v in arr.flatten())
        return f"static const float {name}[{rows}][{cols}] = {{{vals}}};"

    lines = [
        "/**",
        " * dir_gesture_model.h — Auto-generated by train_dir_gesture_svm.py",
        f" * Accuracy : {accuracy*100:.1f}%",
        f" * Features : {N_FEATURES} (f0x,f0y,f1x,f1y,f2x,f2y,f3x,f3y,roll,pitch)",
        f" * Classes  : {N_CLASSES} ({', '.join(DIR_NAMES.values())})",
        " *",
        " * 说明：本文件与 gesture_model.h（gm_前缀）完全独立，专用于方向手势控制。",
        " * STM32 用法：",
        " *   #include \"dir_gesture_model.h\"",
        " *   float feat[DG_N_FEATURES] = {f0x,f0y,f1x,f1y,f2x,f2y,f3x,f3y,roll,pitch};",
        " *   uint8_t dir = DirGesture_Classify(feat);",
        " *   // 0=up  1=down  2=left  3=right  0xFF=失败",
        " */",
        "#ifndef DIR_GESTURE_MODEL_H",
        "#define DIR_GESTURE_MODEL_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define DG_N_FEATURES {N_FEATURES}",
        f"#define DG_N_CLASSES  {N_CLASSES}",
        "",
        "/* StandardScaler 参数 */",
        arr1d(mean_,  "dg_mean"),
        arr1d(scale_, "dg_scale"),
        "",
        "/* LinearSVC 权重 W[class][feature] 和偏置 b[class] */",
        arr2d(W, "dg_W"),
        arr1d(b, "dg_b"),
        "",
        "/* 方向名称（调试用） */",
        "static const char * const dg_labels[DG_N_CLASSES] = {",
    ]
    for k in sorted(DIR_NAMES.keys()):
        lines.append(f'    "{DIR_NAMES[k]}",')
    lines += [
        "};",
        "",
        "/**",
        " * @brief  方向手势 SVM 推理",
        " * @param  feat  长度为 DG_N_FEATURES 的特征数组",
        " *               = {f0x,f0y,f1x,f1y,f2x,f2y,f3x,f3y,roll,pitch}",
        " * @retval 0=up 1=down 2=left 3=right，失败返回 0xFF",
        " */",
        "static inline uint8_t DirGesture_Classify(const float feat[DG_N_FEATURES])",
        "{",
        "    float best_score = -1e30f;",
        "    uint8_t best_cls = 0xFF;",
        "    for (uint8_t k = 0; k < DG_N_CLASSES; k++) {",
        "        float score = dg_b[k];",
        "        for (uint8_t i = 0; i < DG_N_FEATURES; i++) {",
        "            float xn = (feat[i] - dg_mean[i]) / dg_scale[i];",
        "            score += dg_W[k][i] * xn;",
        "        }",
        "        if (score > best_score) {",
        "            best_score = score;",
        "            best_cls   = k;",
        "        }",
        "    }",
        "    return best_cls;",
        "}",
        "",
        "#endif /* DIR_GESTURE_MODEL_H */",
    ]

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\n[导出] 已生成 {output_path}")
    print("  下一步：")
    print("    1. 将 dir_gesture_model.h 复制到 STM32 工程的 HARDWARE/ 目录")
    print("    2. 在 control.c 中 #include \"dir_gesture_model.h\"")
    print("    3. 调用 Gesture_DirControl() 即可（已集成激活逻辑）")


def main():
    parser = argparse.ArgumentParser(description="方向手势 SVM 分类器训练工具")
    parser.add_argument("--data", default="dir_gesture_data.csv", help="输入CSV文件")
    parser.add_argument("--out",  default="dir_gesture_model.h",  help="输出C头文件")
    args = parser.parse_args()

    print("=" * 55)
    print("  方向手势 SVM 分类器训练工具")
    print("=" * 55)

    X, y = load_data(args.data)
    scaler, svm, acc = train_and_evaluate(X, y)
    export_c_header(scaler, svm, args.out, acc)

    print("\n[完成] 请将 dir_gesture_model.h 复制到 STM32 工程的 HARDWARE/ 目录")


if __name__ == "__main__":
    main()
