/**
 * gesture_model.h — Auto-generated by train_svm.py
 * Accuracy: 100.0%
 * Features: 10 (f0x,f0y,f1x,f1y,f2x,f2y,f3x,f3y,roll,pitch)
 * Classes : 5 (fist, open, one, two, rock)
 *
 * Usage in STM32:
 *   #include "gesture_model.h"
 *   uint8_t label = Gesture_Classify(f0,f1,f2,f3,roll,pitch);
 */
#ifndef GESTURE_MODEL_H
#define GESTURE_MODEL_H

#include <stdint.h>

#define GM_N_FEATURES 10
#define GM_N_CLASSES  5

/* --- StandardScaler 参数 --- */
static const float gm_mean[10] = {-10.767063f, 26.157526f, -36.897507f, 10.518040f, -19.505360f, -6.895205f, 17.556446f, -3.242175f, 49.732883f, 5.078964f};
static const float gm_scale[10] = {34.210712f, 8.617653f, 35.901791f, 5.022340f, 45.272282f, 9.813435f, 39.180443f, 6.445978f, 21.406347f, 5.158816f};

/* --- LinearSVC 权重 W[class][feature] 和偏置 b[class] --- */
static const float gm_W[5][10] = {-0.507355f, -0.185651f, 0.099599f, -0.175554f, 0.081709f, 0.166174f, -0.915863f, -0.061245f, 0.432120f, 0.189473f, 0.205343f, -0.092247f, 0.877561f, -0.028177f, 0.271629f, -0.160775f, 0.001179f, 0.021385f, -0.516428f, 0.117513f, -0.939941f, 0.333052f, 0.224534f, 0.032158f, -1.178101f, 0.142779f, 0.802792f, -0.032999f, 0.101770f, 0.120241f, -0.107242f, 0.236935f, -0.729437f, 0.199000f, 1.273965f, -0.075986f, 0.073375f, -0.027207f, -0.151340f, -0.188056f, 1.118512f, -0.355836f, -0.808701f, 0.111537f, -0.423013f, 0.067143f, -0.083156f, -0.006328f, -0.272489f, -0.114594f};
static const float gm_b[5] = {-1.158481f, -0.902468f, -1.102537f, -0.855987f, -0.891479f};

/* --- 手势名称（调试用） --- */
static const char * const gm_labels[GM_N_CLASSES] = {
    "fist",
    "open",
    "one",
    "two",
    "rock",
};

/**
 * @brief  SVM 手势分类推理（纯C，无需外部库）
 * @param  f0x, f0y, f1x, f1y, f2x, f2y, f3x, f3y, roll, pitch
 * @retval 手势类别编号（0~N_CLASSES-1），失败返回 0xFF
 */
static inline uint8_t Gesture_Classify(
    float f0x, float f0y, float f1x, float f1y, float f2x, float f2y, float f3x, float f3y, float roll, float pitch)
{
    float feat[GM_N_FEATURES] = {f0x, f0y, f1x, f1y, f2x, f2y, f3x, f3y, roll, pitch};
    float best_score = -1e30f;
    uint8_t best_cls = 0xFF;
    for (uint8_t k = 0; k < GM_N_CLASSES; k++) {
        /* score = W[k] · x_norm + b[k] */
        float score = gm_b[k];
        for (uint8_t i = 0; i < GM_N_FEATURES; i++) {
            float xn = (feat[i] - gm_mean[i]) / gm_scale[i];
            score += gm_W[k][i] * xn;  /* k*N_FEATURES+i for flat array */
        }
        if (score > best_score) {
            best_score = score;
            best_cls   = k;
        }
    }
    return best_cls;
}

#endif /* GESTURE_MODEL_H */