/**
 * swipe_model.h — Auto-generated by train_swipe_svm.py
 * Accuracy : 97.2%
 * Features : 24 (roll_max, roll_min, roll_range, roll_mean, roll_delta, roll_peak_pos, pitch_max, pitch_min, pitch_range, pitch_mean, pitch_delta, pitch_peak_pos, gyro_z_max, gyro_z_min, gyro_z_range, gyro_z_mean, gyro_z_delta, gyro_z_peak_pos, gyro_y_max, gyro_y_min, gyro_y_range, gyro_y_mean, gyro_y_delta, gyro_y_peak_pos)
 * Classes  : 4 (left, right, up, down)
 *
 * STM32 用法：
 *   #include "swipe_model.h"
 *   // 准备 float feat[SM_N_FEATURES];
 *   // 填入从 WINDOW_SIZE 帧中提取的 24 维特征
 *   uint8_t dir = Swipe_Classify(feat);
 */
#ifndef SWIPE_MODEL_H
#define SWIPE_MODEL_H

#include <stdint.h>

#define SM_N_FEATURES  24
#define SM_N_CLASSES   4
#define SM_WINDOW_SIZE 30
#define SM_N_CHANNELS  4

/* StandardScaler 参数 */
static const float sm_mean[24] = {35.926636f, -6.376262f, 42.302898f, 14.669865f, 5.501122f, 0.430712f, 16.834440f, 0.938131f, 15.896309f, 9.480645f, -0.396402f, 0.483242f, 77.603554f, -80.524109f, 158.127670f, -0.104188f, 3.575234f, 0.545118f, 62.592709f, -77.533829f, 140.126541f, -0.758196f, -0.349860f, 0.528360f};
static const float sm_scale[24] = {14.901196f, 31.145468f, 30.115091f, 17.921648f, 21.609337f, 0.264189f, 5.340353f, 6.536460f, 5.230487f, 5.029406f, 7.493366f, 0.311229f, 33.481014f, 30.062389f, 57.347404f, 8.630693f, 72.955238f, 0.318693f, 18.217005f, 35.131432f, 42.739292f, 4.297881f, 45.991714f, 0.316644f};

/* LinearSVC 权重 W[class][feature] 和偏置 b[class] */
static const float sm_W[4][24] = {-0.125686f, 0.136392f, -0.203249f, 0.035064f, -0.080744f, -0.023284f, -0.286313f, -0.079409f, -0.193091f, -0.070359f, -0.053510f, -0.024391f, 0.291422f, 0.017548f, 0.160941f, 0.414909f, 0.370437f, -0.117761f, -0.062250f, 0.124214f, -0.128636f, -0.138154f, 0.239209f, 0.099100f, -0.042071f, 0.287897f, -0.318564f, 0.371658f, -0.051737f, 0.066056f, 0.280570f, 0.140764f, 0.110553f, 0.110139f, 0.162854f, -0.163656f, 0.003081f, -0.175978f, 0.094049f, -0.608597f, -0.605058f, 0.135805f, -0.011287f, -0.076923f, 0.058419f, 0.271676f, -0.142804f, -0.038673f, 0.884418f, 0.954120f, -0.549148f, -1.193720f, 0.214257f, -0.019744f, 0.065032f, -0.300505f, 0.441934f, -0.226904f, -0.285382f, -0.035010f, -0.843085f, 0.337032f, -0.668894f, -0.115039f, 0.025159f, 0.027519f, 0.352402f, 0.022899f, 0.131384f, -0.084444f, -0.058583f, 0.013857f, -0.353871f, -1.205250f, 1.071388f, 0.176705f, -0.335352f, 0.022671f, -0.027967f, 0.293053f, -0.394778f, 0.032672f, 0.074356f, 0.099489f, 0.061284f, -0.056804f, 0.065557f, 0.308243f, -0.359922f, -0.141007f, -0.233217f, -0.078507f, -0.034873f, 0.077104f, 0.186830f, 0.092618f};
static const float sm_b[4] = {-0.897421f, -0.932894f, -1.532208f, -1.495417f};

/* 方向名称（调试用） */
static const char * const sm_labels[SM_N_CLASSES] = {
    "left",
    "right",
    "up",
    "down",
};

/**
 * @brief  从24维特征向量推理挥手方向
 * @param  feat  长度为 SM_N_FEATURES 的特征数组
 *               特征提取方式见 Swipe_ExtractFeatures() in control.c
 * @retval 0=left 1=right 2=up 3=down，失败返回 0xFF
 */
static inline uint8_t Swipe_Classify(const float feat[SM_N_FEATURES])
{
    float best_score = -1e30f;
    uint8_t best_cls = 0xFF;
    for (uint8_t k = 0; k < SM_N_CLASSES; k++) {
        float score = sm_b[k];
        for (uint8_t i = 0; i < SM_N_FEATURES; i++) {
            float xn = (feat[i] - sm_mean[i]) / sm_scale[i];
            score += sm_W[k][i] * xn;
        }
        if (score > best_score) {
            best_score = score;
            best_cls   = k;
        }
    }
    return best_cls;
}

#endif /* SWIPE_MODEL_H */