/**
 * gesture_model.h — Auto-generated by train_svm.py
 * Accuracy: 100.0%
 * Features: 10 (f0x,f0y,f1x,f1y,f2x,f2y,f3x,f3y,roll,pitch)
 * Classes : 5 (fist, open, one, two, rock)
 *
 * Usage in STM32:
 *   #include "gesture_model.h"
 *   uint8_t label = Gesture_Classify(f0,f1,f2,f3,roll,pitch);
 */
#ifndef GESTURE_MODEL_H
#define GESTURE_MODEL_H

#include <stdint.h>

#define GM_N_FEATURES 10
#define GM_N_CLASSES  5

/* --- StandardScaler 参数 --- */
static const float gm_mean[10] = {-10.594745f, 26.195236f, -37.193115f, 10.712969f, -24.080856f, -7.318488f, 15.281138f, -2.452322f, 48.476410f, 5.780701f};
static const float gm_scale[10] = {35.266830f, 8.835532f, 36.995937f, 4.977423f, 42.766171f, 9.884308f, 39.298664f, 5.642727f, 21.463356f, 4.384568f};

/* --- LinearSVC 权重 W[class][feature] 和偏置 b[class] --- */
static const float gm_W[5][10] = {-0.545586f, -0.162266f, 0.081809f, -0.213440f, 0.134601f, 0.221680f, -0.825625f, -0.111130f, 0.463749f, 0.163671f, 0.212908f, -0.103557f, 0.877230f, -0.035062f, 0.273469f, -0.178599f, -0.010574f, -0.002734f, -0.501211f, 0.145495f, -0.941467f, 0.372949f, 0.237526f, 0.028674f, -1.133190f, 0.130787f, 0.787354f, -0.040038f, 0.097849f, 0.152331f, -0.099098f, 0.244521f, -0.758262f, 0.193877f, 1.208879f, -0.081868f, 0.065962f, -0.012166f, -0.141170f, -0.154777f, 1.141223f, -0.395267f, -0.754047f, 0.096946f, -0.494885f, 0.077789f, -0.099595f, 0.009211f, -0.269683f, -0.074003f};
static const float gm_b[5] = {-1.049330f, -0.890681f, -1.045656f, -0.982394f, -0.859505f};

/* --- 手势名称（调试用） --- */
static const char * const gm_labels[GM_N_CLASSES] = {
    "fist",
    "open",
    "one",
    "two",
    "rock",
};

/**
 * @brief  SVM 手势分类推理（纯C，无需外部库）
 * @param  f0x, f0y, f1x, f1y, f2x, f2y, f3x, f3y, roll, pitch
 * @retval 手势类别编号（0~N_CLASSES-1），失败返回 0xFF
 */
static inline uint8_t Gesture_Classify(
    float f0x, float f0y, float f1x, float f1y, float f2x, float f2y, float f3x, float f3y, float roll, float pitch)
{
    float feat[GM_N_FEATURES] = {f0x, f0y, f1x, f1y, f2x, f2y, f3x, f3y, roll, pitch};
    float best_score = -1e30f;
    uint8_t best_cls = 0xFF;
    for (uint8_t k = 0; k < GM_N_CLASSES; k++) {
        /* score = W[k] · x_norm + b[k] */
        float score = gm_b[k];
        for (uint8_t i = 0; i < GM_N_FEATURES; i++) {
            float xn = (feat[i] - gm_mean[i]) / gm_scale[i];
            score += gm_W[k][i] * xn;  /* k*N_FEATURES+i for flat array */
        }
        if (score > best_score) {
            best_score = score;
            best_cls   = k;
        }
    }
    return best_cls;
}

#endif /* GESTURE_MODEL_H */