/**
 * dir_gesture_model.h — Auto-generated by train_dir_gesture_svm.py
 * Accuracy : 100.0%
 * Features : 10 (f0x,f0y,f1x,f1y,f2x,f2y,f3x,f3y,roll,pitch)
 * Classes  : 4 (up, down, left, right)
 *
 * 说明：本文件与 gesture_model.h（gm_前缀）完全独立，专用于方向手势控制。
 * STM32 用法：
 *   #include "dir_gesture_model.h"
 *   float feat[DG_N_FEATURES] = {f0x,f0y,f1x,f1y,f2x,f2y,f3x,f3y,roll,pitch};
 *   uint8_t dir = DirGesture_Classify(feat);
 *   // 0=up  1=down  2=left  3=right  0xFF=失败
 */
#ifndef DIR_GESTURE_MODEL_H
#define DIR_GESTURE_MODEL_H

#include <stdint.h>

#define DG_N_FEATURES 10
#define DG_N_CLASSES  4

/* StandardScaler 参数 */
static const float dg_mean[10] = {-39.171646f, 22.235361f, -37.644497f, 4.769647f, -25.151554f, 9.642941f, -41.606514f, 5.865428f, 16.559143f, 7.039496f};
static const float dg_scale[10] = {23.277842f, 28.427063f, 20.064835f, 32.442337f, 21.105560f, 28.586035f, 18.282272f, 30.253674f, 27.412251f, 34.108704f};

/* LinearSVC 权重 W[class][feature] 和偏置 b[class] */
static const float dg_W[4][10] = {0.383503f, -0.172517f, -0.377592f, 0.030350f, -0.482912f, -0.154955f, -0.364412f, 0.075070f, 0.376397f, -0.113140f, 0.066782f, -0.287582f, -0.031218f, 0.040311f, 0.396260f, 0.256503f, -0.126449f, 0.240660f, -1.437663f, 0.171067f, -0.744173f, -0.024214f, 0.244277f, -0.374880f, 0.262859f, -0.119246f, 0.090702f, -0.324768f, 0.198001f, -0.224215f, 0.138891f, 0.544647f, 0.268379f, 0.424666f, 0.036663f, 0.341795f, 0.306356f, 0.385299f, 0.558611f, 0.482663f};
static const float dg_b[4] = {-1.148694f, -1.154801f, -1.071538f, -0.904812f};

/* 方向名称（调试用） */
static const char * const dg_labels[DG_N_CLASSES] = {
    "up",
    "down",
    "left",
    "right",
};

/**
 * @brief  方向手势 SVM 推理
 * @param  feat  长度为 DG_N_FEATURES 的特征数组
 *               = {f0x,f0y,f1x,f1y,f2x,f2y,f3x,f3y,roll,pitch}
 * @retval 0=up 1=down 2=left 3=right，失败返回 0xFF
 */
static inline uint8_t DirGesture_Classify(const float feat[DG_N_FEATURES])
{
    float best_score = -1e30f;
    uint8_t best_cls = 0xFF;
    for (uint8_t k = 0; k < DG_N_CLASSES; k++) {
        float score = dg_b[k];
        for (uint8_t i = 0; i < DG_N_FEATURES; i++) {
            float xn = (feat[i] - dg_mean[i]) / dg_scale[i];
            score += dg_W[k][i] * xn;
        }
        if (score > best_score) {
            best_score = score;
            best_cls   = k;
        }
    }
    return best_cls;
}

#endif /* DIR_GESTURE_MODEL_H */