#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

#include "debug_uart/glove_frame.h"
#include "debug_uart/mid_uart.h"
#include "gesture/gesture_service.h"
#include "led/bsp_led.h"

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    glove_frame_t            rx_frame;
    gesture_service_result_t gesture_result;
    fsp_err_t                err = FSP_SUCCESS;

    /*
     * 应用层只负责业务编排：
     * 1. 初始化 LED、串口和手势业务层；
     * 2. 持续接收 STM32 发来的特征帧；
     * 3. 每 100ms 更新一次分类样本；
     * 4. 每 200ms 输出一次分类结果和命令。
     */
    LED_Init();

    /* 串口初始化失败时直接停住，避免后续进入无意义的收包循环。 */
    if (FSP_SUCCESS != MID_Uart_Init())
    {
        while (1)
        {
        }
    }

    /* 手势业务层内部维护 100ms 取样和 200ms 分类节拍。 */
    GestureService_Init();

    /*
     * uart7 作为调试口，启动后先打印提示信息。
     * 这样你接上串口助手后，可以立刻知道瑞萨端已经进入等待收帧状态。
     */
    (void) MID_Uart_SendString(MID_UART_PORT_7, "\r\nRA6M5 gesture classify ready\r\n");
    (void) MID_Uart_SendString(MID_UART_PORT_7, "uart2 keep receiving, sample=100ms, classify=200ms\r\n\r\n");

    while (1)
    {
        /*
         * uart2 持续接收 STM32 发来的固定帧。
         * 这里每收到一帧就立刻交给手势业务层，让业务层自己决定是否更新样本、是否触发分类。
         */
        err = GloveFrame_Receive(MID_UART_PORT_2, &rx_frame);
        if (FSP_SUCCESS != err)
        {
            (void) MID_Uart_SendString(MID_UART_PORT_7, "uart2 receive error\r\n");
            continue;
        }

        err = GestureService_ProcessFrame(&rx_frame, &gesture_result);
        if (FSP_SUCCESS != err)
        {
            (void) MID_Uart_SendString(MID_UART_PORT_7, "gesture process error\r\n");
            continue;
        }

        if (gesture_result.classify_ready)
        {
            /*
             * LED 每完成一次 200ms 分类才翻转一次。
             * 这样肉眼更容易看出系统正在稳定工作，而不是因为 20ms 收包过快导致常亮/常灭错觉。
             */
            LED1_TOGGLE;
            (void) GestureService_PrintResult(MID_UART_PORT_7, &gesture_result);
        }
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* 配置引脚复用，这是 UART、LED 等外设能够工作的前提。 */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable(void);

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable(void)
{
}
FSP_CPP_FOOTER

#endif
