#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

#include "debug_uart/mid_uart.h"
#include "key/bsp_key_irq.h"
#include "led/bsp_led.h"

/* 按键中断文件里定义的按下标志位，这里只读取和清零，不直接修改中断逻辑。 */
extern volatile bool key1_sw2_press;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* 应用层初始化：先启动外设功能，再启动中间层串口服务。 */
    Key_IRQ_Init();
    LED_Init();

    /* 串口初始化失败时停在这里，便于调试阶段快速发现问题。 */
    if (FSP_SUCCESS != MID_Uart_Init())
    {
        while (1)
        {
        }
    }

    /* 上电后先发一条提示信息，方便串口助手确认系统已经启动。 */
    (void) MID_Uart_SendString(MID_UART_PORT_7, "uart middleware ready\r\n");

    while (1)
    {
        if (key1_sw2_press)
        {
            /* 消抖后的动作入口：清标志、翻转 LED、发送测试数据。 */
            key1_sw2_press = false;
            LED1_TOGGLE;

            /* uart7 发送文本浮点数，适合上位机直接显示。 */
            (void) MID_Uart_SendFloatText(MID_UART_PORT_7, 36.58f, 2U, true);
            /* uart2 发送十六进制命令，适合控制外部模块。 */
            (void) MID_Uart_SendHexString(MID_UART_PORT_2, "AA 55 01 02 0D 0A");
        }
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* 配置引脚复用，这是 UART、LED、按键等外设能够工作的前提。 */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable(void);

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable(void)
{
}
FSP_CPP_FOOTER

#endif
