#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

#include "debug_uart/glove_frame.h"
#include "debug_uart/mid_uart.h"
#include "gesture/gesture_service.h"
#include "led/bsp_led.h"
#include "timer/mid_dispatch_timer.h"

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    glove_frame_t            rx_frame;
    gesture_service_result_t gesture_result;
    fsp_err_t                err = FSP_SUCCESS;
    uint8_t                  tx_cmd = 0U;

    /*
     * 应用层只负责业务编排：
     * 1. 初始化 LED、串口、手势业务层和 200ms 定时派发服务；
     * 2. 持续接收 STM32 发来的特征帧；
     * 3. 每收到一帧就交给业务层决定是否更新 100ms 分类样本；
     * 4. 只有定时器累计满 200ms，才允许发一次 16 进制命令；
     * 5. uart7 在当前版本里只发原始命令字节，其他文本一律不发。
     */
    LED_Init();

    /* 串口初始化失败时直接停住，避免后续进入无意义的收包循环。 */
    if (FSP_SUCCESS != MID_Uart_Init())
    {
        while (1)
        {
        }
    }

    /* 手势业务层负责 100ms 取样和命令过滤状态维护。 */
    GestureService_Init();

    /*
     * 中间层定时器服务内部已经接好了：
     * AGT0 10ms 中断 -> 200ms 标志位。
     * 应用层这里不碰 g_timer_agt0，只拿“能不能发一次”这个结果。
     */
    if (FSP_SUCCESS != MID_DispatchTimer_Init())
    {
        while (1)
        {
        }
    }

    while (1)
    {
        /*
         * uart2 持续接收 STM32 发来的固定帧。
         * 这里每收到一帧就立刻交给手势业务层，让业务层自己决定是否更新 100ms 样本。
         */
        err = GloveFrame_Receive(MID_UART_PORT_2, &rx_frame);
        if (FSP_SUCCESS != err)
        {
            continue;
        }

        err = GestureService_ProcessFrame(&rx_frame, &gesture_result);
        if (FSP_SUCCESS != err)
        {
            continue;
        }

        if (MID_DispatchTimer_TryConsumeDispatchFlag())
        {
            /*
             * 只有 200ms 标志到了，才执行一次分类周期。
             * 如果当前结果还在等待确认，或者被过滤成 0x02/0x00，这里就什么都不发。
             */
            err = GestureService_RunClassifyCycle(&gesture_result);
            if (FSP_SUCCESS != err)
            {
                continue;
            }

            if (gesture_result.send_ready)
            {
                tx_cmd = gesture_result.send_cmd;
                LED1_TOGGLE;
                (void) MID_Uart_SendHex(MID_UART_PORT_7, &tx_cmd, 1U);
            }
        }
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* 配置引脚复用，这是 UART、LED 等外设能够工作的前提。 */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable(void);

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable(void)
{
}
FSP_CPP_FOOTER

#endif
